//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globalization.Resources.Comments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globalization.Resources.Comments.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apie.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentuoti.
        /// </summary>
        public static string AddCommentComment {
            get {
                return ResourceManager.GetString("AddCommentComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Šio komentaro tekstas yra paslėptas &gt;.
        /// </summary>
        public static string CommentHidden {
            get {
                return ResourceManager.GetString("CommentHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumentai.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite komentarą.
        /// </summary>
        public static string CommentTextIsRequired {
            get {
                return ResourceManager.GetString("CommentTextIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritikuoju.
        /// </summary>
        public static string Criticize {
            get {
                return ResourceManager.GetString("Criticize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritikuoja.
        /// </summary>
        public static string Criticizes {
            get {
                return ResourceManager.GetString("Criticizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slėpti.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kaip įgyvendinti.
        /// </summary>
        public static string HowToRealize {
            get {
                return ResourceManager.GetString("HowToRealize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sprendimą Nr..
        /// </summary>
        public static string IdeaNo {
            get {
                return ResourceManager.GetString("IdeaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aš palaikau.
        /// </summary>
        public static string LikedComment {
            get {
                return ResourceManager.GetString("LikedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutralus.
        /// </summary>
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutralūs.
        /// </summary>
        public static string Neutrals {
            get {
                return ResourceManager.GetString("Neutrals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerbkime save ir savo kalbą - komentuokime taisyklinga lietuvių kalba!.
        /// </summary>
        public static string RespectLanguage {
            get {
                return ResourceManager.GetString("RespectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodyti.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodyti visus.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodyti visus komentarus.
        /// </summary>
        public static string ShowAllComments {
            get {
                return ResourceManager.GetString("ShowAllComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siūlau.
        /// </summary>
        public static string Suggest {
            get {
                return ResourceManager.GetString("Suggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siūlo.
        /// </summary>
        public static string Suggests {
            get {
                return ResourceManager.GetString("Suggests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palaikau.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palaiko.
        /// </summary>
        public static string Supports {
            get {
                return ResourceManager.GetString("Supports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jeigu norite komentuoti.
        /// </summary>
        public static string ToComment {
            get {
                return ResourceManager.GetString("ToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atšaukti.
        /// </summary>
        public static string UndoLikeComment {
            get {
                return ResourceManager.GetString("UndoLikeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rašo.
        /// </summary>
        public static string Writes {
            get {
                return ResourceManager.GetString("Writes", resourceCulture);
            }
        }
    }
}
