JavaScriptLibraryResources = {
"DecimalSeparator": ",",
"DateSeparator": "-",
"PhoneSeparators": " ()+-",
"GroupSeparator": ".",
"DoYouWantToContinue": "Do you want to continue?",
"AllowedDateSeparators": ".,/- ",
"SymbolsLeft":"$ symbols left",
"Yes": "Year",
"No": "No",
"Cancel": "Cancel",
"ConfirmDelete": "Are you sure you want to delete this? This action cannot be undone.",
"ShowMore": "More",
"Close": "Close",
"Save": "Save",
"Agree": "Agree",
"AllCategories": "All categories",
"NumberOfCategories": "Number of categories: ",
"CategoriesSaved": "Category selection saved successfully",
"SelectCategory": "Select a category",
"CannotDelete": "Cannot delete this item",
"GoogleConnectConfirm": "If you connect to Google Drive, the text you've entered will be lost. Do you want to continue?",
"SomeoneElseConnectedToFb": " is connected with the current Facebook user. Do you want to change this?",
"ErrorOccurred": "Error occurred - the last action failed",
"SelectCategories": "Select categories",
"NoCategories": "No categories found",
"ChooseCategory": "Select category..",
"Help": "Help",
"LanguageCode": "en",
"Send": "Send",
"Users": "Users",
"AllStates": "All states",
"StateCount": "Selected states: ",
"OK": "OK"
}
