JavaScriptLibraryResources = {
"DecimalSeparator": ",",
"DateSeparator": "-",
"PhoneSeparators": " ()+-",
"GroupSeparator": ".",
"DoYouWantToContinue": "Ar norite tęsti?",
"AllowedDateSeparators": ".,/- ",
"SymbolsLeft":"Liko: $",
"Yes": "Taip",
"No": "Ne",
"Cancel": "Atšaukti",
"ConfirmDelete": "Ar tikrai norite pašalinti įrašą? Šios operacijos nebus galima atšaukti.",
"ShowMore": "Daugiau",
"Close": "Uždaryti",
"Save": "Saugoti",
"Agree": "Sutinku",
"AllCategories": "Visos kategorijos",
"NumberOfCategories": "Kategorijų skaičius: ",
"CategoriesSaved": "Kategorijų pasirinkimas sėkmingai išsaugotas",
"SelectCategory": "Pasirinkite",
"CannotDelete": "Šio įrašo pašalinti negalima.",
"GoogleConnectConfirm": "Prisijungus prie Google Drive, bus prarastas Jūsų įvestas tekstas. Ar tikrai norite tęsti?",
"SomeoneElseConnectedToFb": " priskirtas dabartiniam facebook naudotojui. Ar norite jį perskirti?",
"ErrorOccurred": "Įvyko klaida - komandos įvykdyti nepavyko.",
"SelectCategories": "Pasirinkite kategorijas",
"NoCategories": "Nėra rezultatų, tenkinančių sąlygą",
"ChooseCategory": "Pasirinkite..",
"Help": "Pagalba",
"LanguageCode": "lt",
"Send": "Siųsti",
"Users": "Naudotojai",
"AllStates": "Visos būsenos",
"StateCount": "Būsenų skaičius: ",
"OK": "Gerai"

}
