//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globalization.Resources.Problem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globalization.Resources.Problem.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodomos kategorijos.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentuoti.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarai.
        /// </summary>
        public static string CommentsCount {
            get {
                return ResourceManager.GetString("CommentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įtraukti naują.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukurti pasiūlymą.
        /// </summary>
        public static string CreateIdea {
            get {
                return ResourceManager.GetString("CreateIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprašyti balsavimą.
        /// </summary>
        public static string CreateIssue {
            get {
                return ResourceManager.GetString("CreateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprašyti naują balsavimą.
        /// </summary>
        public static string CreateTooltip {
            get {
                return ResourceManager.GetString("CreateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neaktualu.
        /// </summary>
        public static string Downvote {
            get {
                return ResourceManager.GetString("Downvote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite komentarą.
        /// </summary>
        public static string EnterComment {
            get {
                return ResourceManager.GetString("EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite tekstą.
        /// </summary>
        public static string EnterProbelm {
            get {
                return ResourceManager.GetString("EnterProbelm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Išskleisti.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualūs.
        /// </summary>
        public static string FilterInteresting {
            get {
                return ResourceManager.GetString("FilterInteresting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mano miestai.
        /// </summary>
        public static string FilterLocal {
            get {
                return ResourceManager.GetString("FilterLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiti.
        /// </summary>
        public static string FilterOther {
            get {
                return ResourceManager.GetString("FilterOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekami.
        /// </summary>
        public static string FilterSubscribed {
            get {
                return ResourceManager.GetString("FilterSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daugiau komentarų.
        /// </summary>
        public static string MoreComments {
            get {
                return ResourceManager.GetString("MoreComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pažymėkite, ar šis pasisakymas yra nacionalinio masto, ar skirtas konkrečiai savivaldybei?.
        /// </summary>
        public static string MunicipalityIdHelp {
            get {
                return ResourceManager.GetString("MunicipalityIdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasisakymų pagal pasirinktus nustatymus nėra.
        /// </summary>
        public static string NoProblems {
            get {
                return ResourceManager.GetString("NoProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasiūlyti sprendimą.
        /// </summary>
        public static string OfferSolution {
            get {
                return ResourceManager.GetString("OfferSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacija.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kieno vardu pasisakoma?.
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įkelti į facebook.
        /// </summary>
        public static string PostToFacebook {
            get {
                return ResourceManager.GetString("PostToFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kas vyksta?.
        /// </summary>
        public static string ProblemInputPlaceholder {
            get {
                return ResourceManager.GetString("ProblemInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Susieti pasiūlymą.
        /// </summary>
        public static string RelateIdea {
            get {
                return ResourceManager.GetString("RelateIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasirinkite sprendimą.
        /// </summary>
        public static string SelectIdea {
            get {
                return ResourceManager.GetString("SelectIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priskirkite pasisakymą.
        /// </summary>
        public static string SelectProblem {
            get {
                return ResourceManager.GetString("SelectProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodyti visus.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaip siūloma spręsti?.
        /// </summary>
        public static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualiausi.
        /// </summary>
        public static string SortActive {
            get {
                return ResourceManager.GetString("SortActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naujausi.
        /// </summary>
        public static string SortNearest {
            get {
                return ResourceManager.GetString("SortNearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liko.
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasisakymai.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualu.
        /// </summary>
        public static string Upvote {
            get {
                return ResourceManager.GetString("Upvote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peržiūros.
        /// </summary>
        public static string ViewsCount {
            get {
                return ResourceManager.GetString("ViewsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viso balsavo.
        /// </summary>
        public static string VotesCount {
            get {
                return ResourceManager.GetString("VotesCount", resourceCulture);
            }
        }
    }
}
