//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF.Voting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idea
    {
        public Idea()
        {
            this.IdeaCategories = new HashSet<IdeaCategory>();
            this.IdeaComments = new HashSet<IdeaComment>();
            this.IdeaIssues = new HashSet<IdeaIssue>();
            this.IdeaPriorities = new HashSet<IdeaPriority>();
            this.IdeaVersions = new HashSet<IdeaVersion>();
            this.IdeaVotes = new HashSet<IdeaVote>();
            this.ProblemIdeas = new HashSet<ProblemIdea>();
            this.RelatedIdeas = new HashSet<RelatedIdea>();
            this.RelatedIdeas1 = new HashSet<RelatedIdea>();
        }
    
        public string Id { get; set; }
        public string Subject { get; set; }
        public string Aim { get; set; }
        public string UserObjectId { get; set; }
        public bool IsDraft { get; set; }
        public string OrganizationId { get; set; }
        public bool IsPrivate { get; set; }
        public Nullable<int> MunicipalityId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<int> RequiredVotes { get; set; }
        public int StateId { get; set; }
        public string FinalIdeaText { get; set; }
        public string FinalVersionId { get; set; }
        public bool IsImpersonal { get; set; }
    
        public virtual ICollection<IdeaCategory> IdeaCategories { get; set; }
        public virtual ICollection<IdeaComment> IdeaComments { get; set; }
        public virtual ICollection<IdeaIssue> IdeaIssues { get; set; }
        public virtual ICollection<IdeaPriority> IdeaPriorities { get; set; }
        public virtual IdeaVersion IdeaVersion { get; set; }
        public virtual ICollection<IdeaVersion> IdeaVersions { get; set; }
        public virtual ICollection<IdeaVote> IdeaVotes { get; set; }
        public virtual ICollection<ProblemIdea> ProblemIdeas { get; set; }
        public virtual ICollection<RelatedIdea> RelatedIdeas { get; set; }
        public virtual ICollection<RelatedIdea> RelatedIdeas1 { get; set; }
    }
}
