//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF.Actions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Categories_Translation = new HashSet<Categories_Translation>();
            this.InterestingCategories = new HashSet<InterestingCategory>();
            this.ActionCategories = new HashSet<ActionCategory>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Categories_Translation> Categories_Translation { get; set; }
        public virtual ICollection<InterestingCategory> InterestingCategories { get; set; }
        public virtual ICollection<ActionCategory> ActionCategories { get; set; }
    }
}
