//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globalization.Resources.Organization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globalization.Resources.Organization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresas.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turi likti bent vienas administratorius.
        /// </summary>
        public static string AdministratorRequired {
            get {
                return ResourceManager.GetString("AdministratorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jau pakviesti.
        /// </summary>
        public static string AlreadyInvited {
            get {
                return ResourceManager.GetString("AlreadyInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norėdami sukurti organizaciją, turite patvirtinti tapatybę.
        /// </summary>
        public static string CannotCreate {
            get {
                return ResourceManager.GetString("CannotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktinė informacija.
        /// </summary>
        public static string ContactsLegend {
            get {
                return ResourceManager.GetString("ContactsLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukurti.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukurti naują.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukurti naują organizaciją.
        /// </summary>
        public static string CreateNewToolTip {
            get {
                return ResourceManager.GetString("CreateNewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauja organizacija.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprašymas.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite aprašymą.
        /// </summary>
        public static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El. paštas.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El. pašto adresai.
        /// </summary>
        public static string EmailAddresses {
            get {
                return ResourceManager.GetString("EmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite po vieną organizacijos nario el. pašto adresą eilutėje.
        /// </summary>
        public static string EmailAddressesHelp {
            get {
                return ResourceManager.GetString("EmailAddressesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite el. paštą.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingas el. pašto formatas.
        /// </summary>
        public static string EmailRegexpIsNotValid {
            get {
                return ResourceManager.GetString("EmailRegexpIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiklą vykdo nuo.
        /// </summary>
        public static string FoundedOn {
            get {
                return ResourceManager.GetString("FoundedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tikslai.
        /// </summary>
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacijos.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacija apie organizaciją.
        /// </summary>
        public static string InfoLegend {
            get {
                return ResourceManager.GetString("InfoLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite aprašymą.
        /// </summary>
        public static string InsertSubjectIsRequired {
            get {
                return ResourceManager.GetString("InsertSubjectIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žinutė.
        /// </summary>
        public static string InvitationMessage {
            get {
                return ResourceManager.GetString("InvitationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite žinutę, kurią norite įtraukti į pakvietimą.
        /// </summary>
        public static string InvitationMessageHelp {
            get {
                return ResourceManager.GetString("InvitationMessageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvietimai.
        /// </summary>
        public static string Invitations {
            get {
                return ResourceManager.GetString("Invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kviesti.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakvietė.
        /// </summary>
        public static string InvitedBy {
            get {
                return ResourceManager.GetString("InvitedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapti nariu.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapti organizacijos nariu. Reikės esamų organizacijos narių patvirtinimo..
        /// </summary>
        public static string JoinOrganizationToolTip {
            get {
                return ResourceManager.GetString("JoinOrganizationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palikti organizaciją.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Išeiti iš organizacijos.
        /// </summary>
        public static string LeaveToolTip {
            get {
                return ResourceManager.GetString("LeaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palaikau.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palaikau šią organizaciją, noriu būti infromuojamas apie jos veiklą.
        /// </summary>
        public static string LikeOrganizationToolTip {
            get {
                return ResourceManager.GetString("LikeOrganizationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narių veikla.
        /// </summary>
        public static string MemberActivity {
            get {
                return ResourceManager.GetString("MemberActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matomas viešai.
        /// </summary>
        public static string MemberIsPublic {
            get {
                return ResourceManager.GetString("MemberIsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misija.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pavadinimas.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite pavadinimą.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palaikančiųjų skaičius.
        /// </summary>
        public static string NumberOfSupporters {
            get {
                return ResourceManager.GetString("NumberOfSupporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veikla.
        /// </summary>
        public static string OrganizationActivity {
            get {
                return ResourceManager.GetString("OrganizationActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasiūlymai.
        /// </summary>
        public static string OrganizationIdeas {
            get {
                return ResourceManager.GetString("OrganizationIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacija.
        /// </summary>
        public static string OrganizationInfo {
            get {
                return ResourceManager.GetString("OrganizationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balsavimai.
        /// </summary>
        public static string OrganizationIssues {
            get {
                return ResourceManager.GetString("OrganizationIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nariai.
        /// </summary>
        public static string OrganizationMembers {
            get {
                return ResourceManager.GetString("OrganizationMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasisakymai.
        /// </summary>
        public static string OrganizationProblems {
            get {
                return ResourceManager.GetString("OrganizationProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projektai.
        /// </summary>
        public static string OrganizationProjects {
            get {
                return ResourceManager.GetString("OrganizationProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacijos.
        /// </summary>
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Organizacija.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel. nr..
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingas tel. numerio formatas.
        /// </summary>
        public static string PhoneNumberRegexpIsNotValid {
            get {
                return ResourceManager.GetString("PhoneNumberRegexpIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pareigos.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matomas tik organizacijos nariams.
        /// </summary>
        public static string PrivateToOrganization {
            get {
                return ResourceManager.GetString("PrivateToOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacijos logo.
        /// </summary>
        public static string ProfilePictureLegend {
            get {
                return ResourceManager.GetString("ProfilePictureLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekto pašalinti nepavyko..
        /// </summary>
        public static string ProjectDeleteFailed {
            get {
                return ResourceManager.GetString("ProjectDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruoti nariai.
        /// </summary>
        public static string RegisteredMembers {
            get {
                return ResourceManager.GetString("RegisteredMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite registruoto Lietuva 2.0 naudotojo vardą, pavardę.
        /// </summary>
        public static string RegisteredMembersHelp {
            get {
                return ResourceManager.GetString("RegisteredMembersHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakartoti.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siųsti pakvietimą dar kartą.
        /// </summary>
        public static string RepeatHelp {
            get {
                return ResourceManager.GetString("RepeatHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolė.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipas.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atšaukti palaikymą.
        /// </summary>
        public static string Unlike {
            get {
                return ResourceManager.GetString("Unlike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebenoriu būti informuojamas apie organizacijos veiklą.
        /// </summary>
        public static string UnlikeToolTip {
            get {
                return ResourceManager.GetString("UnlikeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite nuorodą.
        /// </summary>
        public static string UrlIsRequired {
            get {
                return ResourceManager.GetString("UrlIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizija.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palaukite, kol Jūsų narystė organizacijoje bus patvirtinta. Jeigu nesate organizacijos narys, rekomenduojame užsipildyti savo paskyrą bei išsiųsti motyvacinį laišką organizacijos vadovui..
        /// </summary>
        public static string WaitForApproval {
            get {
                return ResourceManager.GetString("WaitForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuorodos.
        /// </summary>
        public static string Websites {
            get {
                return ResourceManager.GetString("Websites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pavadinimas.
        /// </summary>
        public static string WebSiteTitle {
            get {
                return ResourceManager.GetString("WebSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuoroda.
        /// </summary>
        public static string WebSiteUrl {
            get {
                return ResourceManager.GetString("WebSiteUrl", resourceCulture);
            }
        }
    }
}
