//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globalization.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActionDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globalization.Resources.Services.ActionDescriptions", typeof(ActionDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pasikeitė savo nuotrauką.
        /// </summary>
        public static string ChangedProfilePicture {
            get {
                return ResourceManager.GetString("ChangedProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pateikė komentarą apie piliečio {2} argumentą dėl {1}.
        /// </summary>
        public static string CommentCommented {
            get {
                return ResourceManager.GetString("CommentCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sutinka su {2} pateiktu {1} argumento komentaru.
        /// </summary>
        public static string CommentCommentLiked {
            get {
                return ResourceManager.GetString("CommentCommentLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} argumentavo teisės aktą {1}.
        /// </summary>
        public static string Commented {
            get {
                return ResourceManager.GetString("Commented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} klausimais, susijusiais su {3}, bus atstovaujamas piliečio {2}.
        /// </summary>
        public static string DelegatedVote {
            get {
                return ResourceManager.GetString("DelegatedVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} argumentavo sprendimą {1}.
        /// </summary>
        public static string IdeaCommented {
            get {
                return ResourceManager.GetString("IdeaCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sutinka su {2} argumentu dėl {1}.
        /// </summary>
        public static string IdeaCommentLiked {
            get {
                return ResourceManager.GetString("IdeaCommentLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pateikė naują pasiūlymą {1}.
        /// </summary>
        public static string IdeaCreated {
            get {
                return ResourceManager.GetString("IdeaCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pakoregavo pasiūlymą {1}.
        /// </summary>
        public static string IdeaEdited {
            get {
                return ResourceManager.GetString("IdeaEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pakeitė pasiūlymo {1} būseną.
        /// </summary>
        public static string IdeaStateChanged {
            get {
                return ResourceManager.GetString("IdeaStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pasiūlė naują sprendimą pasiūlymui {1}.
        /// </summary>
        public static string IdeaVersionAdded {
            get {
                return ResourceManager.GetString("IdeaVersionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paredagavo pasiūlymo {1} sprendimą.
        /// </summary>
        public static string IdeaVersionEdited {
            get {
                return ResourceManager.GetString("IdeaVersionEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} palaiko pasiūlymo {1} sprendimą.
        /// </summary>
        public static string IdeaVersionLiked {
            get {
                return ResourceManager.GetString("IdeaVersionLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} peržiūrėjo pasiūlymą {1}.
        /// </summary>
        public static string IdeaViewed {
            get {
                return ResourceManager.GetString("IdeaViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pateikė balsavimui naują teisės aktą {1}.
        /// </summary>
        public static string IssueCreated {
            get {
                return ResourceManager.GetString("IssueCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paredagavo balsavimą {1}.
        /// </summary>
        public static string IssueEdited {
            get {
                return ResourceManager.GetString("IssueEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pažymėjo, kad valdžia balsavo dėl {1}.
        /// </summary>
        public static string IssueOfficialyVoted {
            get {
                return ResourceManager.GetString("IssueOfficialyVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} peržiūrėjo balsavimą {1}.
        /// </summary>
        public static string IssueViewed {
            get {
                return ResourceManager.GetString("IssueViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} prisijungė prie projekto {1} įgyvendinimo.
        /// </summary>
        public static string JoinedProject {
            get {
                return ResourceManager.GetString("JoinedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} domisi kategorija (-jom) {3}.
        /// </summary>
        public static string LikedCategory {
            get {
                return ResourceManager.GetString("LikedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sutinka su {2} argumentu dėl {1}.
        /// </summary>
        public static string LikedComment {
            get {
                return ResourceManager.GetString("LikedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} domisi sistemos naudotojo {2} veikla.
        /// </summary>
        public static string LikedUser {
            get {
                return ResourceManager.GetString("LikedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sukūrė naują organizaciją {5}.
        /// </summary>
        public static string OrganizationCreated {
            get {
                return ResourceManager.GetString("OrganizationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} prisijungė prie organizacijos {5}.
        /// </summary>
        public static string OrganizationJoined {
            get {
                return ResourceManager.GetString("OrganizationJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pretenduoja tapti organizacijos {5} nariu.
        /// </summary>
        public static string OrganizationJoining {
            get {
                return ResourceManager.GetString("OrganizationJoining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} palaiko organizaciją {5}.
        /// </summary>
        public static string OrganizationLiked {
            get {
                return ResourceManager.GetString("OrganizationLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} buvo piliečio {0} paskirtas(-i) organizacijos {5} nariu (-ais).
        /// </summary>
        public static string OrganizationMemberAdded {
            get {
                return ResourceManager.GetString("OrganizationMemberAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} buvo piliečio {0} pašalintas iš kandidatų į organizacijos {5} narius.
        /// </summary>
        public static string OrganizationMemberRejected {
            get {
                return ResourceManager.GetString("OrganizationMemberRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} atnaujino organizacijos {5} narių informaciją.
        /// </summary>
        public static string OrganizationMemberRolesUpdated {
            get {
                return ResourceManager.GetString("OrganizationMemberRolesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sukūrė naują organizacijos {5} projektą {1}.
        /// </summary>
        public static string OrganizationProjectAdded {
            get {
                return ResourceManager.GetString("OrganizationProjectAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pakeitė organizacijos {5} projekto {1} būseną.
        /// </summary>
        public static string OrganizationProjectStateChanged {
            get {
                return ResourceManager.GetString("OrganizationProjectStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paskyrė {2} naują organizacijos {5} projekto {1} užduotį.
        /// </summary>
        public static string OrganizationToDoAdded {
            get {
                return ResourceManager.GetString("OrganizationToDoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} komentavo organizacijos {5} projekto {1} užduotį {4}.
        /// </summary>
        public static string OrganizationToDoCommentAdded {
            get {
                return ResourceManager.GetString("OrganizationToDoCommentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paredagavo {2} skirtą organizacijos {5} projekto {1} užduotį.
        /// </summary>
        public static string OrganizationToDoEdited {
            get {
                return ResourceManager.GetString("OrganizationToDoEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} atliko organizacijos {5} projekto {1} užduotį.
        /// </summary>
        public static string OrganizationToDoFinished {
            get {
                return ResourceManager.GetString("OrganizationToDoFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ėmėsi vykdyti organizacijos {5} projekto {1} užduotį.
        /// </summary>
        public static string OrganizationToDoTaken {
            get {
                return ResourceManager.GetString("OrganizationToDoTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} atnaujino organizacijos {5} duomenis.
        /// </summary>
        public static string OrganizationUpdated {
            get {
                return ResourceManager.GetString("OrganizationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} peržiūrėjo organizacijos {5} informaciją.
        /// </summary>
        public static string OrganizationViewed {
            get {
                return ResourceManager.GetString("OrganizationViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} komentavo pasisakymą.
        /// </summary>
        public static string ProblemCommented {
            get {
                return ResourceManager.GetString("ProblemCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sutinka su piliečio {2} komentaru.
        /// </summary>
        public static string ProblemCommentLiked {
            get {
                return ResourceManager.GetString("ProblemCommentLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pasisakė.
        /// </summary>
        public static string ProblemCreated {
            get {
                return ResourceManager.GetString("ProblemCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nepalaiko pasisakymo.
        /// </summary>
        public static string ProblemDevoted {
            get {
                return ResourceManager.GetString("ProblemDevoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} susiejo pasiūlymą {4} su pasisakymu.
        /// </summary>
        public static string ProblemIdeaAssigned {
            get {
                return ResourceManager.GetString("ProblemIdeaAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} palaiko pasisakymą.
        /// </summary>
        public static string ProblemVoted {
            get {
                return ResourceManager.GetString("ProblemVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} importavo savo paskyros duomenis iš LinkedIn.
        /// </summary>
        public static string ProfileImportedFromLinkedIn {
            get {
                return ResourceManager.GetString("ProfileImportedFromLinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} buvo piliečio {0} paskirtas(-i) projekto {1} komandos nariu (-ais).
        /// </summary>
        public static string ProjectMemberAdded {
            get {
                return ResourceManager.GetString("ProjectMemberAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} susiejo pasiūlymą {1} su kitu pasiūlymu (-ais).
        /// </summary>
        public static string RelatedIdeaAdded {
            get {
                return ResourceManager.GetString("RelatedIdeaAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} susiejo pasiūlymą {1} su balsavimu(-ais).
        /// </summary>
        public static string RelatedIssueAdded {
            get {
                return ResourceManager.GetString("RelatedIssueAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sukūrė naują balsavimo {1} aprašymo versiją.
        /// </summary>
        public static string SummaryVersionAdded {
            get {
                return ResourceManager.GetString("SummaryVersionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paskyrė {2} naują projekto {1} užduotį.
        /// </summary>
        public static string ToDoAdded {
            get {
                return ResourceManager.GetString("ToDoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} komentavo projekto {1} užduotį {4}.
        /// </summary>
        public static string ToDoCommentAdded {
            get {
                return ResourceManager.GetString("ToDoCommentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paredagavo {2} skirtą projekto {1} užduotį.
        /// </summary>
        public static string ToDoEdited {
            get {
                return ResourceManager.GetString("ToDoEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} atliko projekto {1} užduotį.
        /// </summary>
        public static string ToDoFinished {
            get {
                return ResourceManager.GetString("ToDoFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ėmėsi vykdyti projekto {1} užduotį.
        /// </summary>
        public static string ToDoTaken {
            get {
                return ResourceManager.GetString("ToDoTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} atnaujino savo kontaktus.
        /// </summary>
        public static string UpdatedContacts {
            get {
                return ResourceManager.GetString("UpdatedContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} atnaujino savo išsilavinimą ir darbo patirtį.
        /// </summary>
        public static string UpdatedEducationAndWork {
            get {
                return ResourceManager.GetString("UpdatedEducationAndWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} atnaujino savo domėjimosi sritis.
        /// </summary>
        public static string UpdatedInterests {
            get {
                return ResourceManager.GetString("UpdatedInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} atnaujino savo asmeninę informaciją.
        /// </summary>
        public static string UpdatedPersonalInfo {
            get {
                return ResourceManager.GetString("UpdatedPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} gavo Lietuva 2.0 titulą.
        /// </summary>
        public static string UserAwarded {
            get {
                return ResourceManager.GetString("UserAwarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pareiškė savo nuomonę apie pilietį {1}.
        /// </summary>
        public static string UserCommented {
            get {
                return ResourceManager.GetString("UserCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sutinka su {2} nuomone apie pilietį {1}.
        /// </summary>
        public static string UserCommentLiked {
            get {
                return ResourceManager.GetString("UserCommentLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} prisijungė prie Lietuva 2.0.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} peržiūrėjo piliečio (-ės) {2} informaciją.
        /// </summary>
        public static string UserProfileViewed {
            get {
                return ResourceManager.GetString("UserProfileViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} balsavo dėl {1}.
        /// </summary>
        public static string Voted {
            get {
                return ResourceManager.GetString("Voted", resourceCulture);
            }
        }
    }
}
