//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globalization.Resources.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserDeleteReasons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserDeleteReasons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globalization.Resources.Services.UserDeleteReasons", typeof(UserDeleteReasons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenoriu/negaliu patvirtinti el. pašto.
        /// </summary>
        public static string CannotConfirm {
            get {
                return ResourceManager.GetString("CannotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portale keliamos iniciatyvos prieštarauja mano pažiūroms ir įsitikinimams.
        /// </summary>
        public static string DifferentViews {
            get {
                return ResourceManager.GetString("DifferentViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užsiregistravau daugiau nei vieną kartą.
        /// </summary>
        public static string DuplicatedAccount {
            get {
                return ResourceManager.GetString("DuplicatedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buvau įžeistas kitų Lietuva 2.0 bendruomenės narių.
        /// </summary>
        public static string Insulted {
            get {
                return ResourceManager.GetString("Insulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manęs nedomina portale vykdoma veikla.
        /// </summary>
        public static string NotInterested {
            get {
                return ResourceManager.GetString("NotInterested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kita.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mano Lietuva 2.0 paskyra yra rodoma paieškos sistemose.
        /// </summary>
        public static string SearchEngines {
            get {
                return ResourceManager.GetString("SearchEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užsiregistravau netyčia.
        /// </summary>
        public static string UnintendedRegistration {
            get {
                return ResourceManager.GetString("UnintendedRegistration", resourceCulture);
            }
        }
    }
}
