//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globalization.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globalization.Resources.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridėti įrašą.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridėti nuorodą.
        /// </summary>
        public static string AddLink {
            get {
                return ResourceManager.GetString("AddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridėti.
        /// </summary>
        public static string AddShort {
            get {
                return ResourceManager.GetString("AddShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sutinku.
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visos kategorijos.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visi.
        /// </summary>
        public static string AllMale {
            get {
                return ResourceManager.GetString("AllMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atgal.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atšaukti.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacija negalima.
        /// </summary>
        public static string Cheating {
            get {
                return ResourceManager.GetString("Cheating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įveskite komentarą.
        /// </summary>
        public static string CommentIsRequired {
            get {
                return ResourceManager.GetString("CommentIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentarai.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patvirtinti.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar tikrai norite siųsti laiškus?.
        /// </summary>
        public static string ConfirmSendMail {
            get {
                return ResourceManager.GetString("ConfirmSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminas.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šalinti.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redaguoti.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redaguoti visą.
        /// </summary>
        public static string EditAll {
            get {
                return ResourceManager.GetString("EditAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redaguoti aprašymą.
        /// </summary>
        public static string EditDescription {
            get {
                return ResourceManager.GetString("EditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaida.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprašyti plačiau.
        /// </summary>
        public static string ExtendedView {
            get {
                return ResourceManager.GetString("ExtendedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScriptLibraryResources.js.
        /// </summary>
        public static string JavascriptGlobalizationFile {
            get {
                return ResourceManager.GetString("JavascriptGlobalizationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lt-LT.
        /// </summary>
        public static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lt.
        /// </summary>
        public static string LanguageCodeShort {
            get {
                return ResourceManager.GetString("LanguageCodeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sutinku.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daugiau.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mano kategorijos.
        /// </summary>
        public static string MyCategories {
            get {
                return ResourceManager.GetString("MyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toliau.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenustatyta dabartinė gyvenamoji arba gimtoji vietos. Nustatykite jas savo asmeniniame puslapyje..
        /// </summary>
        public static string NoCities {
            get {
                return ResourceManager.GetString("NoCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitos kategorijos.
        /// </summary>
        public static string NotMyCategories {
            get {
                return ResourceManager.GetString("NotMyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be ID.
        /// </summary>
        public static string NotUnique {
            get {
                return ResourceManager.GetString("NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacija sėkminga.
        /// </summary>
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arba.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kita.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atgal.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skelbti.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saugoti.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duomenys išsaugoti sėkmingai.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paieška.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siųsti.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patyrę Lietuva 2.0 bendruomenės nariai turi galimybę išsiųst informacinius pranešimus apie naujai sukurtą įrašą kitiems bendruomenės nariams. Šis veiksmas yra vienkartinis, o jį įvykdžius, laišku bus informuoti visi, kas domisi šio įrašo kategorijomis. Siųskite laiškus tik apie tvarkingus, pilnus, neturinčius gramatinių klaidų ir, Jūsų nuomone, vertingus įrašus, ir nevykdykite šios komandos dažniau nei kartą į parą..
        /// </summary>
        public static string SendMailTip {
            get {
                return ResourceManager.GetString("SendMailTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lietuva 2.0.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekti naujienas.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekti.
        /// </summary>
        public static string SubscribeShort {
            get {
                return ResourceManager.GetString("SubscribeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ačiū.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praėjo.
        /// </summary>
        public static string TimeAfter {
            get {
                return ResourceManager.GetString("TimeAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liko.
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viso įrašų.
        /// </summary>
        public static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Į viršų.
        /// </summary>
        public static string ToTop {
            get {
                return ResourceManager.GetString("ToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atšaukti.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to su ID.
        /// </summary>
        public static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebesekti naujienų.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesekti.
        /// </summary>
        public static string UnsubscribeShort {
            get {
                return ResourceManager.GetString("UnsubscribeShort", resourceCulture);
            }
        }
    }
}
