// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Web.Controllers
{
    public partial class OrganizationController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected OrganizationController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Details()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetOrganizationInfo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOrganizationInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Info()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Info);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Contacts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Contacts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveInfo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveContacts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveContacts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditInfo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditContacts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditContacts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveProfilePicture()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveProfilePicture);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Like()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Like);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Unlike()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Unlike);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Join()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Join);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Leave()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Leave);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ConfirmMember()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfirmMember);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RejectMember()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RejectMember);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CancelMembersEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CancelMembersEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveMembers()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveMembers);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetMembersEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetMembersEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddProject()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProject);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ToDos()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ToDos);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddToDo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddToDo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult FinishTodo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FinishTodo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteToDo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteToDo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetToDoEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetToDoEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditToDo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditToDo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReorderToDos()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReorderToDos);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Comments()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Comments);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SaveTempModel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveTempModel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Settings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Settings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddInvitedUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddInvitedUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InviteUsers()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InviteUsers);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReInvite()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReInvite);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoveMember()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveMember);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteProject()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteProject);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetProjects()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProjects);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TakeToDo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TakeToDo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteInvitedUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteInvitedUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetMemberVisibility()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetMemberVisibility);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult RedirectToSuccessAction()
        {
            return new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.RedirectToSuccessAction);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult RedirectToFailureAction()
        {
            return new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.RedirectToFailureAction);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult SaveAndRedirect()
        {
            return new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.SaveAndRedirect);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult DeleteAndRedirect()
        {
            return new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.DeleteAndRedirect);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Back()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Back);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public OrganizationController Actions { get { return MVC.Organization; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Organization";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Organization";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Details = "Details";
            public readonly string GetOrganizationInfo = "GetOrganizationInfo";
            public readonly string Info = "Info";
            public readonly string Contacts = "Contacts";
            public readonly string SaveInfo = "SaveInfo";
            public readonly string SaveContacts = "SaveContacts";
            public readonly string EditInfo = "EditInfo";
            public readonly string EditContacts = "EditContacts";
            public readonly string SaveProfilePicture = "SaveProfilePicture";
            public readonly string Like = "Like";
            public readonly string Unlike = "Unlike";
            public readonly string Join = "Join";
            public readonly string Leave = "Leave";
            public readonly string ConfirmMember = "ConfirmMember";
            public readonly string RejectMember = "RejectMember";
            public readonly string Create = "Create";
            public readonly string CancelMembersEdit = "CancelMembersEdit";
            public readonly string SaveMembers = "SaveMembers";
            public readonly string GetMembersEdit = "GetMembersEdit";
            public readonly string AddProject = "AddProject";
            public readonly string ToDos = "ToDos";
            public readonly string AddToDo = "AddToDo";
            public readonly string FinishTodo = "FinishTodo";
            public readonly string DeleteToDo = "DeleteToDo";
            public readonly string GetToDoEdit = "GetToDoEdit";
            public readonly string EditToDo = "EditToDo";
            public readonly string ReorderToDos = "ReorderToDos";
            public readonly string Comments = "Comments";
            public readonly string AddComment = "AddComment";
            public readonly string SaveTempModel = "SaveTempModel";
            public readonly string DeleteComment = "DeleteComment";
            public readonly string Settings = "Settings";
            public readonly string AddInvitedUser = "AddInvitedUser";
            public readonly string InviteUsers = "InviteUsers";
            public readonly string ReInvite = "ReInvite";
            public readonly string RemoveMember = "RemoveMember";
            public readonly string DeleteProject = "DeleteProject";
            public readonly string GetProjects = "GetProjects";
            public readonly string Delete = "Delete";
            public readonly string TakeToDo = "TakeToDo";
            public readonly string DeleteInvitedUser = "DeleteInvitedUser";
            public readonly string SetMemberVisibility = "SetMemberVisibility";
            public readonly string UpdateAllPictures = "UpdateAllPictures";
            public readonly string RedirectToSuccessAction = "RedirectToSuccessAction";
            public readonly string RedirectToFailureAction = "RedirectToFailureAction";
            public readonly string SaveAndRedirect = "SaveAndRedirect";
            public readonly string DeleteAndRedirect = "DeleteAndRedirect";
            public readonly string Back = "Back";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Details = "Details";
            public const string GetOrganizationInfo = "GetOrganizationInfo";
            public const string Info = "Info";
            public const string Contacts = "Contacts";
            public const string SaveInfo = "SaveInfo";
            public const string SaveContacts = "SaveContacts";
            public const string EditInfo = "EditInfo";
            public const string EditContacts = "EditContacts";
            public const string SaveProfilePicture = "SaveProfilePicture";
            public const string Like = "Like";
            public const string Unlike = "Unlike";
            public const string Join = "Join";
            public const string Leave = "Leave";
            public const string ConfirmMember = "ConfirmMember";
            public const string RejectMember = "RejectMember";
            public const string Create = "Create";
            public const string CancelMembersEdit = "CancelMembersEdit";
            public const string SaveMembers = "SaveMembers";
            public const string GetMembersEdit = "GetMembersEdit";
            public const string AddProject = "AddProject";
            public const string ToDos = "ToDos";
            public const string AddToDo = "AddToDo";
            public const string FinishTodo = "FinishTodo";
            public const string DeleteToDo = "DeleteToDo";
            public const string GetToDoEdit = "GetToDoEdit";
            public const string EditToDo = "EditToDo";
            public const string ReorderToDos = "ReorderToDos";
            public const string Comments = "Comments";
            public const string AddComment = "AddComment";
            public const string SaveTempModel = "SaveTempModel";
            public const string DeleteComment = "DeleteComment";
            public const string Settings = "Settings";
            public const string AddInvitedUser = "AddInvitedUser";
            public const string InviteUsers = "InviteUsers";
            public const string ReInvite = "ReInvite";
            public const string RemoveMember = "RemoveMember";
            public const string DeleteProject = "DeleteProject";
            public const string GetProjects = "GetProjects";
            public const string Delete = "Delete";
            public const string TakeToDo = "TakeToDo";
            public const string DeleteInvitedUser = "DeleteInvitedUser";
            public const string SetMemberVisibility = "SetMemberVisibility";
            public const string UpdateAllPictures = "UpdateAllPictures";
            public const string RedirectToSuccessAction = "RedirectToSuccessAction";
            public const string RedirectToFailureAction = "RedirectToFailureAction";
            public const string SaveAndRedirect = "SaveAndRedirect";
            public const string DeleteAndRedirect = "DeleteAndRedirect";
            public const string Back = "Back";
        }


        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string objectId = "objectId";
            public readonly string name = "name";
            public readonly string view = "view";
            public readonly string ideaSort = "ideaSort";
            public readonly string issueSort = "issueSort";
            public readonly string problemSort = "problemSort";
        }
        static readonly ActionParamsClass_GetOrganizationInfo s_params_GetOrganizationInfo = new ActionParamsClass_GetOrganizationInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOrganizationInfo GetOrganizationInfoParams { get { return s_params_GetOrganizationInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOrganizationInfo
        {
            public readonly string objectId = "objectId";
        }
        static readonly ActionParamsClass_Info s_params_Info = new ActionParamsClass_Info();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Info InfoParams { get { return s_params_Info; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Info
        {
            public readonly string objectId = "objectId";
        }
        static readonly ActionParamsClass_Contacts s_params_Contacts = new ActionParamsClass_Contacts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Contacts ContactsParams { get { return s_params_Contacts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Contacts
        {
            public readonly string objectId = "objectId";
        }
        static readonly ActionParamsClass_SaveInfo s_params_SaveInfo = new ActionParamsClass_SaveInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveInfo SaveInfoParams { get { return s_params_SaveInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveInfo
        {
            public readonly string info = "info";
        }
        static readonly ActionParamsClass_SaveContacts s_params_SaveContacts = new ActionParamsClass_SaveContacts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveContacts SaveContactsParams { get { return s_params_SaveContacts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveContacts
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_EditInfo s_params_EditInfo = new ActionParamsClass_EditInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditInfo EditInfoParams { get { return s_params_EditInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditInfo
        {
            public readonly string objectId = "objectId";
        }
        static readonly ActionParamsClass_EditContacts s_params_EditContacts = new ActionParamsClass_EditContacts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditContacts EditContactsParams { get { return s_params_EditContacts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditContacts
        {
            public readonly string objectId = "objectId";
        }
        static readonly ActionParamsClass_SaveProfilePicture s_params_SaveProfilePicture = new ActionParamsClass_SaveProfilePicture();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveProfilePicture SaveProfilePictureParams { get { return s_params_SaveProfilePicture; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveProfilePicture
        {
            public readonly string objectId = "objectId";
            public readonly string hpf = "hpf";
        }
        static readonly ActionParamsClass_Like s_params_Like = new ActionParamsClass_Like();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Like LikeParams { get { return s_params_Like; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Like
        {
            public readonly string objectId = "objectId";
        }
        static readonly ActionParamsClass_Unlike s_params_Unlike = new ActionParamsClass_Unlike();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Unlike UnlikeParams { get { return s_params_Unlike; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Unlike
        {
            public readonly string objectId = "objectId";
        }
        static readonly ActionParamsClass_Join s_params_Join = new ActionParamsClass_Join();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Join JoinParams { get { return s_params_Join; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Join
        {
            public readonly string objectId = "objectId";
        }
        static readonly ActionParamsClass_Leave s_params_Leave = new ActionParamsClass_Leave();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Leave LeaveParams { get { return s_params_Leave; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Leave
        {
            public readonly string objectId = "objectId";
        }
        static readonly ActionParamsClass_ConfirmMember s_params_ConfirmMember = new ActionParamsClass_ConfirmMember();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ConfirmMember ConfirmMemberParams { get { return s_params_ConfirmMember; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ConfirmMember
        {
            public readonly string organizationId = "organizationId";
            public readonly string userObjectId = "userObjectId";
        }
        static readonly ActionParamsClass_RejectMember s_params_RejectMember = new ActionParamsClass_RejectMember();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RejectMember RejectMemberParams { get { return s_params_RejectMember; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RejectMember
        {
            public readonly string organizationId = "organizationId";
            public readonly string userObjectId = "userObjectId";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_CancelMembersEdit s_params_CancelMembersEdit = new ActionParamsClass_CancelMembersEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CancelMembersEdit CancelMembersEditParams { get { return s_params_CancelMembersEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CancelMembersEdit
        {
            public readonly string organizationId = "organizationId";
        }
        static readonly ActionParamsClass_SaveMembers s_params_SaveMembers = new ActionParamsClass_SaveMembers();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveMembers SaveMembersParams { get { return s_params_SaveMembers; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveMembers
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetMembersEdit s_params_GetMembersEdit = new ActionParamsClass_GetMembersEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetMembersEdit GetMembersEditParams { get { return s_params_GetMembersEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetMembersEdit
        {
            public readonly string organizationId = "organizationId";
        }
        static readonly ActionParamsClass_AddProject s_params_AddProject = new ActionParamsClass_AddProject();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddProject AddProjectParams { get { return s_params_AddProject; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddProject
        {
            public readonly string organizationId = "organizationId";
            public readonly string projectName = "projectName";
            public readonly string isPrivate = "isPrivate";
        }
        static readonly ActionParamsClass_ToDos s_params_ToDos = new ActionParamsClass_ToDos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ToDos ToDosParams { get { return s_params_ToDos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ToDos
        {
            public readonly string organizationId = "organizationId";
            public readonly string projectId = "projectId";
        }
        static readonly ActionParamsClass_AddToDo s_params_AddToDo = new ActionParamsClass_AddToDo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddToDo AddToDoParams { get { return s_params_AddToDo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddToDo
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_FinishTodo s_params_FinishTodo = new ActionParamsClass_FinishTodo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FinishTodo FinishTodoParams { get { return s_params_FinishTodo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FinishTodo
        {
            public readonly string organizationId = "organizationId";
            public readonly string projectId = "projectId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteToDo s_params_DeleteToDo = new ActionParamsClass_DeleteToDo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteToDo DeleteToDoParams { get { return s_params_DeleteToDo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteToDo
        {
            public readonly string organizationId = "organizationId";
            public readonly string projectId = "projectId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetToDoEdit s_params_GetToDoEdit = new ActionParamsClass_GetToDoEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetToDoEdit GetToDoEditParams { get { return s_params_GetToDoEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetToDoEdit
        {
            public readonly string organizationId = "organizationId";
            public readonly string projectId = "projectId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditToDo s_params_EditToDo = new ActionParamsClass_EditToDo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditToDo EditToDoParams { get { return s_params_EditToDo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditToDo
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ReorderToDos s_params_ReorderToDos = new ActionParamsClass_ReorderToDos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReorderToDos ReorderToDosParams { get { return s_params_ReorderToDos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReorderToDos
        {
            public readonly string organizationId = "organizationId";
            public readonly string projectId = "projectId";
            public readonly string startPos = "startPos";
            public readonly string endPos = "endPos";
        }
        static readonly ActionParamsClass_Comments s_params_Comments = new ActionParamsClass_Comments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Comments CommentsParams { get { return s_params_Comments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Comments
        {
            public readonly string organizationId = "organizationId";
            public readonly string projectId = "projectId";
            public readonly string toDoId = "toDoId";
        }
        static readonly ActionParamsClass_AddComment s_params_AddComment = new ActionParamsClass_AddComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddComment AddCommentParams { get { return s_params_AddComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddComment
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SaveTempModel s_params_SaveTempModel = new ActionParamsClass_SaveTempModel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveTempModel SaveTempModelParams { get { return s_params_SaveTempModel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveTempModel
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteComment s_params_DeleteComment = new ActionParamsClass_DeleteComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteComment DeleteCommentParams { get { return s_params_DeleteComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteComment
        {
            public readonly string organizationId = "organizationId";
            public readonly string projectId = "projectId";
            public readonly string toDoId = "toDoId";
            public readonly string commentId = "commentId";
        }
        static readonly ActionParamsClass_Settings s_params_Settings = new ActionParamsClass_Settings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Settings SettingsParams { get { return s_params_Settings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Settings
        {
            public readonly string organizationId = "organizationId";
            public readonly string projectId = "projectId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddInvitedUser s_params_AddInvitedUser = new ActionParamsClass_AddInvitedUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddInvitedUser AddInvitedUserParams { get { return s_params_AddInvitedUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddInvitedUser
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_InviteUsers s_params_InviteUsers = new ActionParamsClass_InviteUsers();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InviteUsers InviteUsersParams { get { return s_params_InviteUsers; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InviteUsers
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ReInvite s_params_ReInvite = new ActionParamsClass_ReInvite();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReInvite ReInviteParams { get { return s_params_ReInvite; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReInvite
        {
            public readonly string organizationId = "organizationId";
            public readonly string userEmail = "userEmail";
        }
        static readonly ActionParamsClass_RemoveMember s_params_RemoveMember = new ActionParamsClass_RemoveMember();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveMember RemoveMemberParams { get { return s_params_RemoveMember; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveMember
        {
            public readonly string organizationId = "organizationId";
            public readonly string userId = "userId";
        }
        static readonly ActionParamsClass_DeleteProject s_params_DeleteProject = new ActionParamsClass_DeleteProject();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteProject DeleteProjectParams { get { return s_params_DeleteProject; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteProject
        {
            public readonly string organizationId = "organizationId";
            public readonly string projectId = "projectId";
        }
        static readonly ActionParamsClass_GetProjects s_params_GetProjects = new ActionParamsClass_GetProjects();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetProjects GetProjectsParams { get { return s_params_GetProjects; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetProjects
        {
            public readonly string organizationId = "organizationId";
            public readonly string view = "view";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string objectId = "objectId";
        }
        static readonly ActionParamsClass_TakeToDo s_params_TakeToDo = new ActionParamsClass_TakeToDo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TakeToDo TakeToDoParams { get { return s_params_TakeToDo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TakeToDo
        {
            public readonly string organizationId = "organizationId";
            public readonly string projectId = "projectId";
            public readonly string toDoId = "toDoId";
        }
        static readonly ActionParamsClass_DeleteInvitedUser s_params_DeleteInvitedUser = new ActionParamsClass_DeleteInvitedUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteInvitedUser DeleteInvitedUserParams { get { return s_params_DeleteInvitedUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteInvitedUser
        {
            public readonly string organizationId = "organizationId";
            public readonly string email = "email";
        }
        static readonly ActionParamsClass_SetMemberVisibility s_params_SetMemberVisibility = new ActionParamsClass_SetMemberVisibility();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetMemberVisibility SetMemberVisibilityParams { get { return s_params_SetMemberVisibility; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetMemberVisibility
        {
            public readonly string organizationId = "organizationId";
            public readonly string userId = "userId";
            public readonly string isPublic = "isPublic";
        }
        static readonly ActionParamsClass_RedirectToSuccessAction s_params_RedirectToSuccessAction = new ActionParamsClass_RedirectToSuccessAction();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RedirectToSuccessAction RedirectToSuccessActionParams { get { return s_params_RedirectToSuccessAction; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RedirectToSuccessAction
        {
            public readonly string result = "result";
            public readonly string message = "message";
            public readonly string openDialog = "openDialog";
            public readonly string routeValueDictionary = "routeValueDictionary";
        }
        static readonly ActionParamsClass_RedirectToFailureAction s_params_RedirectToFailureAction = new ActionParamsClass_RedirectToFailureAction();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RedirectToFailureAction RedirectToFailureActionParams { get { return s_params_RedirectToFailureAction; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RedirectToFailureAction
        {
            public readonly string result = "result";
            public readonly string message = "message";
            public readonly string openDialog = "openDialog";
            public readonly string routeValueDictionary = "routeValueDictionary";
        }
        static readonly ActionParamsClass_SaveAndRedirect s_params_SaveAndRedirect = new ActionParamsClass_SaveAndRedirect();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveAndRedirect SaveAndRedirectParams { get { return s_params_SaveAndRedirect; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveAndRedirect
        {
            public readonly string save = "save";
            public readonly string result = "result";
            public readonly string routeValueDictionary = "routeValueDictionary";
        }
        static readonly ActionParamsClass_DeleteAndRedirect s_params_DeleteAndRedirect = new ActionParamsClass_DeleteAndRedirect();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAndRedirect DeleteAndRedirectParams { get { return s_params_DeleteAndRedirect; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAndRedirect
        {
            public readonly string delete = "delete";
            public readonly string result = "result";
            public readonly string routeValueDictionary = "routeValueDictionary";
        }
        static readonly ActionParamsClass_Back s_params_Back = new ActionParamsClass_Back();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Back BackParams { get { return s_params_Back; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Back
        {
            public readonly string returnTo = "returnTo";
            public readonly string defaultReturnTo = "defaultReturnTo";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ConfirmedMembers = "ConfirmedMembers";
                public readonly string Contacts = "Contacts";
                public readonly string ContactsEdit = "ContactsEdit";
                public readonly string Create = "Create";
                public readonly string CreateForm = "CreateForm";
                public readonly string Details = "Details";
                public readonly string Ideas = "Ideas";
                public readonly string Index = "Index";
                public readonly string Info = "Info";
                public readonly string InfoEdit = "InfoEdit";
                public readonly string Issues = "Issues";
                public readonly string Members = "Members";
                public readonly string MembersEdit = "MembersEdit";
                public readonly string OrganizationInfo = "OrganizationInfo";
                public readonly string Problems = "Problems";
                public readonly string Results = "Results";
            }
            public readonly string ConfirmedMembers = "~/Views/Organization/ConfirmedMembers.cshtml";
            public readonly string Contacts = "~/Views/Organization/Contacts.cshtml";
            public readonly string ContactsEdit = "~/Views/Organization/ContactsEdit.cshtml";
            public readonly string Create = "~/Views/Organization/Create.cshtml";
            public readonly string CreateForm = "~/Views/Organization/CreateForm.cshtml";
            public readonly string Details = "~/Views/Organization/Details.cshtml";
            public readonly string Ideas = "~/Views/Organization/Ideas.cshtml";
            public readonly string Index = "~/Views/Organization/Index.cshtml";
            public readonly string Info = "~/Views/Organization/Info.cshtml";
            public readonly string InfoEdit = "~/Views/Organization/InfoEdit.cshtml";
            public readonly string Issues = "~/Views/Organization/Issues.cshtml";
            public readonly string Members = "~/Views/Organization/Members.cshtml";
            public readonly string MembersEdit = "~/Views/Organization/MembersEdit.cshtml";
            public readonly string OrganizationInfo = "~/Views/Organization/OrganizationInfo.cshtml";
            public readonly string Problems = "~/Views/Organization/Problems.cshtml";
            public readonly string Results = "~/Views/Organization/Results.cshtml";
            static readonly _ProjectClass s_Project = new _ProjectClass();
            public _ProjectClass Project { get { return s_Project; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ProjectClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Comment = "Comment";
                    public readonly string Comments = "Comments";
                    public readonly string EditToDoItem = "EditToDoItem";
                    public readonly string FinishedToDoItem = "FinishedToDoItem";
                    public readonly string Menu = "Menu";
                    public readonly string ProjectListContainer = "ProjectListContainer";
                    public readonly string ProjectListItem = "ProjectListItem";
                    public readonly string Projects = "Projects";
                    public readonly string Settings = "Settings";
                    public readonly string ToDoItem = "ToDoItem";
                    public readonly string ToDos = "ToDos";
                }
                public readonly string Comment = "~/Views/Organization/Project/Comment.cshtml";
                public readonly string Comments = "~/Views/Organization/Project/Comments.cshtml";
                public readonly string EditToDoItem = "~/Views/Organization/Project/EditToDoItem.cshtml";
                public readonly string FinishedToDoItem = "~/Views/Organization/Project/FinishedToDoItem.cshtml";
                public readonly string Menu = "~/Views/Organization/Project/Menu.cshtml";
                public readonly string ProjectListContainer = "~/Views/Organization/Project/ProjectListContainer.cshtml";
                public readonly string ProjectListItem = "~/Views/Organization/Project/ProjectListItem.cshtml";
                public readonly string Projects = "~/Views/Organization/Project/Projects.cshtml";
                public readonly string Settings = "~/Views/Organization/Project/Settings.cshtml";
                public readonly string ToDoItem = "~/Views/Organization/Project/ToDoItem.cshtml";
                public readonly string ToDos = "~/Views/Organization/Project/ToDos.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_OrganizationController : Web.Controllers.OrganizationController
    {
        public T4MVC_OrganizationController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId, string name, Data.Enums.OrganizationViews? view, Services.Enums.IdeaListSorts? ideaSort, Services.Enums.IssueListSorts? issueSort, Services.Enums.ProblemListSorts? problemSort);

        [NonAction]
        public override System.Web.Mvc.ActionResult Details(string objectId, string name, Data.Enums.OrganizationViews? view, Services.Enums.IdeaListSorts? ideaSort, Services.Enums.IssueListSorts? issueSort, Services.Enums.ProblemListSorts? problemSort)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "view", view);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ideaSort", ideaSort);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "issueSort", issueSort);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "problemSort", problemSort);
            DetailsOverride(callInfo, objectId, name, view, ideaSort, issueSort, problemSort);
            return callInfo;
        }

        [NonAction]
        partial void GetOrganizationInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOrganizationInfo(string objectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOrganizationInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            GetOrganizationInfoOverride(callInfo, objectId);
            return callInfo;
        }

        [NonAction]
        partial void InfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Info(string objectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Info);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            InfoOverride(callInfo, objectId);
            return callInfo;
        }

        [NonAction]
        partial void ContactsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Contacts(string objectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Contacts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            ContactsOverride(callInfo, objectId);
            return callInfo;
        }

        [NonAction]
        partial void SaveInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Data.ViewModels.Organization.InfoEditModel info);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveInfo(Data.ViewModels.Organization.InfoEditModel info)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "info", info);
            SaveInfoOverride(callInfo, info);
            return callInfo;
        }

        [NonAction]
        partial void SaveContactsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Data.ViewModels.Organization.ContactsEditModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveContacts(Data.ViewModels.Organization.ContactsEditModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveContacts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveContactsOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EditInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditInfo(string objectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            EditInfoOverride(callInfo, objectId);
            return callInfo;
        }

        [NonAction]
        partial void EditContactsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditContacts(string objectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditContacts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            EditContactsOverride(callInfo, objectId);
            return callInfo;
        }

        [NonAction]
        partial void SaveProfilePictureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId, System.Web.HttpPostedFileBase hpf);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveProfilePicture(string objectId, System.Web.HttpPostedFileBase hpf)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveProfilePicture);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "hpf", hpf);
            SaveProfilePictureOverride(callInfo, objectId, hpf);
            return callInfo;
        }

        [NonAction]
        partial void LikeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Like(string objectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Like);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            LikeOverride(callInfo, objectId);
            return callInfo;
        }

        [NonAction]
        partial void UnlikeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Unlike(string objectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Unlike);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            UnlikeOverride(callInfo, objectId);
            return callInfo;
        }

        [NonAction]
        partial void JoinOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Join(string objectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Join);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            JoinOverride(callInfo, objectId);
            return callInfo;
        }

        [NonAction]
        partial void LeaveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Leave(string objectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Leave);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            LeaveOverride(callInfo, objectId);
            return callInfo;
        }

        [NonAction]
        partial void ConfirmMemberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string userObjectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ConfirmMember(string organizationId, string userObjectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfirmMember);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userObjectId", userObjectId);
            ConfirmMemberOverride(callInfo, organizationId, userObjectId);
            return callInfo;
        }

        [NonAction]
        partial void RejectMemberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string userObjectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult RejectMember(string organizationId, string userObjectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RejectMember);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userObjectId", userObjectId);
            RejectMemberOverride(callInfo, organizationId, userObjectId);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Data.ViewModels.Organization.OrganizationCreateModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create(Data.ViewModels.Organization.OrganizationCreateModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CreateOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void CancelMembersEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId);

        [NonAction]
        public override System.Web.Mvc.ActionResult CancelMembersEdit(string organizationId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CancelMembersEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            CancelMembersEditOverride(callInfo, organizationId);
            return callInfo;
        }

        [NonAction]
        partial void SaveMembersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Data.ViewModels.Organization.OrganizationViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveMembers(Data.ViewModels.Organization.OrganizationViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveMembers);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveMembersOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetMembersEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetMembersEdit(string organizationId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetMembersEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            GetMembersEditOverride(callInfo, organizationId);
            return callInfo;
        }

        [NonAction]
        partial void AddProjectOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string projectName, bool isPrivate);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddProject(string organizationId, string projectName, bool isPrivate)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddProject);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectName", projectName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isPrivate", isPrivate);
            AddProjectOverride(callInfo, organizationId, projectName, isPrivate);
            return callInfo;
        }

        [NonAction]
        partial void ToDosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string projectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ToDos(string organizationId, string projectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ToDos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectId", projectId);
            ToDosOverride(callInfo, organizationId, projectId);
            return callInfo;
        }

        [NonAction]
        partial void AddToDoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Data.ViewModels.Organization.Project.ProjectToDosModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddToDo(Data.ViewModels.Organization.Project.ProjectToDosModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddToDo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddToDoOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void FinishTodoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string projectId, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult FinishTodo(string organizationId, string projectId, string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FinishTodo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectId", projectId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            FinishTodoOverride(callInfo, organizationId, projectId, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteToDoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string projectId, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteToDo(string organizationId, string projectId, string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteToDo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectId", projectId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteToDoOverride(callInfo, organizationId, projectId, id);
            return callInfo;
        }

        [NonAction]
        partial void GetToDoEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string projectId, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetToDoEdit(string organizationId, string projectId, string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetToDoEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectId", projectId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetToDoEditOverride(callInfo, organizationId, projectId, id);
            return callInfo;
        }

        [NonAction]
        partial void EditToDoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Data.ViewModels.Organization.Project.EditToDoModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditToDo(Data.ViewModels.Organization.Project.EditToDoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditToDo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditToDoOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ReorderToDosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string projectId, int startPos, int endPos);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReorderToDos(string organizationId, string projectId, int startPos, int endPos)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReorderToDos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectId", projectId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "startPos", startPos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "endPos", endPos);
            ReorderToDosOverride(callInfo, organizationId, projectId, startPos, endPos);
            return callInfo;
        }

        [NonAction]
        partial void CommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string projectId, string toDoId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Comments(string organizationId, string projectId, string toDoId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Comments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectId", projectId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "toDoId", toDoId);
            CommentsOverride(callInfo, organizationId, projectId, toDoId);
            return callInfo;
        }

        [NonAction]
        partial void AddCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Data.ViewModels.Organization.Project.CommentsModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddComment(Data.ViewModels.Organization.Project.CommentsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddCommentOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void SaveTempModelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Data.ViewModels.Organization.Project.CommentsModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveTempModel(Data.ViewModels.Organization.Project.CommentsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveTempModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveTempModelOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string projectId, string toDoId, string commentId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteComment(string organizationId, string projectId, string toDoId, string commentId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectId", projectId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "toDoId", toDoId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "commentId", commentId);
            DeleteCommentOverride(callInfo, organizationId, projectId, toDoId, commentId);
            return callInfo;
        }

        [NonAction]
        partial void SettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string projectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Settings(string organizationId, string projectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Settings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectId", projectId);
            SettingsOverride(callInfo, organizationId, projectId);
            return callInfo;
        }

        [NonAction]
        partial void SettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Data.ViewModels.Organization.Project.SettingsModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Settings(Data.ViewModels.Organization.Project.SettingsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Settings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SettingsOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void AddInvitedUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Data.ViewModels.Base.InviteUserModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddInvitedUser(Data.ViewModels.Base.InviteUserModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddInvitedUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddInvitedUserOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void InviteUsersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Data.ViewModels.Organization.OrganizationViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult InviteUsers(Data.ViewModels.Organization.OrganizationViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InviteUsers);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            InviteUsersOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ReInviteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string userEmail);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReInvite(string organizationId, string userEmail)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReInvite);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userEmail", userEmail);
            ReInviteOverride(callInfo, organizationId, userEmail);
            return callInfo;
        }

        [NonAction]
        partial void RemoveMemberOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, int? userId);

        [NonAction]
        public override System.Web.Mvc.ActionResult RemoveMember(string organizationId, int? userId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveMember);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            RemoveMemberOverride(callInfo, organizationId, userId);
            return callInfo;
        }

        [NonAction]
        partial void DeleteProjectOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string projectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteProject(string organizationId, string projectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteProject);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectId", projectId);
            DeleteProjectOverride(callInfo, organizationId, projectId);
            return callInfo;
        }

        [NonAction]
        partial void GetProjectsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, Services.Enums.ProjectListViews view);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetProjects(string organizationId, Services.Enums.ProjectListViews view)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProjects);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "view", view);
            GetProjectsOverride(callInfo, organizationId, view);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string objectId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Delete(string objectId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectId", objectId);
            DeleteOverride(callInfo, objectId);
            return callInfo;
        }

        [NonAction]
        partial void TakeToDoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string projectId, string toDoId);

        [NonAction]
        public override System.Web.Mvc.ActionResult TakeToDo(string organizationId, string projectId, string toDoId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TakeToDo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "projectId", projectId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "toDoId", toDoId);
            TakeToDoOverride(callInfo, organizationId, projectId, toDoId);
            return callInfo;
        }

        [NonAction]
        partial void DeleteInvitedUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, string email);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteInvitedUser(string organizationId, string email)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteInvitedUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "email", email);
            DeleteInvitedUserOverride(callInfo, organizationId, email);
            return callInfo;
        }

        [NonAction]
        partial void SetMemberVisibilityOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string organizationId, int userId, bool isPublic);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetMemberVisibility(string organizationId, int userId, bool isPublic)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetMemberVisibility);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "organizationId", organizationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isPublic", isPublic);
            SetMemberVisibilityOverride(callInfo, organizationId, userId, isPublic);
            return callInfo;
        }

        [NonAction]
        partial void UpdateAllPicturesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateAllPictures()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateAllPictures);
            UpdateAllPicturesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RedirectToSuccessActionOverride(T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult callInfo, System.Web.Mvc.ActionResult result, string message, bool openDialog);

        [NonAction]
        public override Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult RedirectToSuccessAction(System.Web.Mvc.ActionResult result, string message, bool openDialog)
        {
            var callInfo = new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.RedirectToSuccessAction);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "result", result);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "openDialog", openDialog);
            RedirectToSuccessActionOverride(callInfo, result, message, openDialog);
            return callInfo;
        }

        [NonAction]
        partial void RedirectToSuccessActionOverride(T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult callInfo, System.Web.Mvc.ActionResult result, bool openDialog);

        [NonAction]
        public override Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult RedirectToSuccessAction(System.Web.Mvc.ActionResult result, bool openDialog)
        {
            var callInfo = new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.RedirectToSuccessAction);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "result", result);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "openDialog", openDialog);
            RedirectToSuccessActionOverride(callInfo, result, openDialog);
            return callInfo;
        }

        [NonAction]
        partial void RedirectToFailureActionOverride(T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult callInfo, System.Web.Mvc.ActionResult result, string message, bool openDialog);

        [NonAction]
        public override Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult RedirectToFailureAction(System.Web.Mvc.ActionResult result, string message, bool openDialog)
        {
            var callInfo = new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.RedirectToFailureAction);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "result", result);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "openDialog", openDialog);
            RedirectToFailureActionOverride(callInfo, result, message, openDialog);
            return callInfo;
        }

        [NonAction]
        partial void SaveAndRedirectOverride(T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult callInfo, System.Action save, System.Web.Mvc.ActionResult result);

        [NonAction]
        public override Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult SaveAndRedirect(System.Action save, System.Web.Mvc.ActionResult result)
        {
            var callInfo = new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.SaveAndRedirect);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "save", save);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "result", result);
            SaveAndRedirectOverride(callInfo, save, result);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAndRedirectOverride(T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult callInfo, System.Action delete, System.Web.Mvc.ActionResult result);

        [NonAction]
        public override Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult DeleteAndRedirect(System.Action delete, System.Web.Mvc.ActionResult result)
        {
            var callInfo = new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.DeleteAndRedirect);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "delete", delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "result", result);
            DeleteAndRedirectOverride(callInfo, delete, result);
            return callInfo;
        }

        [NonAction]
        partial void BackOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnTo, string defaultReturnTo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Back(string returnTo, string defaultReturnTo)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Back);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnTo", returnTo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "defaultReturnTo", defaultReturnTo);
            BackOverride(callInfo, returnTo, defaultReturnTo);
            return callInfo;
        }

        [NonAction]
        partial void RedirectToSuccessActionOverride(T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult callInfo, System.Web.Routing.RouteValueDictionary routeValueDictionary, string message, bool openDialog);

        [NonAction]
        public override Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult RedirectToSuccessAction(System.Web.Routing.RouteValueDictionary routeValueDictionary, string message, bool openDialog)
        {
            var callInfo = new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.RedirectToSuccessAction);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "routeValueDictionary", routeValueDictionary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "openDialog", openDialog);
            RedirectToSuccessActionOverride(callInfo, routeValueDictionary, message, openDialog);
            return callInfo;
        }

        [NonAction]
        partial void RedirectToSuccessActionOverride(T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult callInfo, System.Web.Routing.RouteValueDictionary routeValueDictionary, bool openDialog);

        [NonAction]
        public override Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult RedirectToSuccessAction(System.Web.Routing.RouteValueDictionary routeValueDictionary, bool openDialog)
        {
            var callInfo = new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.RedirectToSuccessAction);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "routeValueDictionary", routeValueDictionary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "openDialog", openDialog);
            RedirectToSuccessActionOverride(callInfo, routeValueDictionary, openDialog);
            return callInfo;
        }

        [NonAction]
        partial void RedirectToFailureActionOverride(T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult callInfo, System.Web.Routing.RouteValueDictionary routeValueDictionary, string message, bool openDialog);

        [NonAction]
        public override Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult RedirectToFailureAction(System.Web.Routing.RouteValueDictionary routeValueDictionary, string message, bool openDialog)
        {
            var callInfo = new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.RedirectToFailureAction);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "routeValueDictionary", routeValueDictionary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "message", message);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "openDialog", openDialog);
            RedirectToFailureActionOverride(callInfo, routeValueDictionary, message, openDialog);
            return callInfo;
        }

        [NonAction]
        partial void SaveAndRedirectOverride(T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult callInfo, System.Action save, System.Web.Routing.RouteValueDictionary routeValueDictionary);

        [NonAction]
        public override Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult SaveAndRedirect(System.Action save, System.Web.Routing.RouteValueDictionary routeValueDictionary)
        {
            var callInfo = new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.SaveAndRedirect);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "save", save);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "routeValueDictionary", routeValueDictionary);
            SaveAndRedirectOverride(callInfo, save, routeValueDictionary);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAndRedirectOverride(T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult callInfo, System.Action delete, System.Web.Routing.RouteValueDictionary routeValueDictionary);

        [NonAction]
        public override Framework.Mvc.ActionResults.RedirectToRouteWithTempDataResult DeleteAndRedirect(System.Action delete, System.Web.Routing.RouteValueDictionary routeValueDictionary)
        {
            var callInfo = new T4MVC_Framework_Mvc_ActionResults_RedirectToRouteWithTempDataResult(Area, Name, ActionNames.DeleteAndRedirect);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "delete", delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "routeValueDictionary", routeValueDictionary);
            DeleteAndRedirectOverride(callInfo, delete, routeValueDictionary);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
